# Generated by Django 5.2.13 on 2026-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'allviews_product',
                'managed': False,
            },
        ),
    ]
